backend:
  name: github
  repo: freedmand/hugotest
  branch: master

media_folder: "static/media/uploads"
public_folder: "/media/uploads"

collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: false
    fields:
      - {label: "Kind", name: "kind", widget: "hidden", default: "about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}